#!/bin/bash
# author: dpit(https://dpit.lib00.com)
# this sh file for auto renew ssl file(generated by acme.sh docker) to synology DSM 7.2
# 此 sh 文件用于自动更新 ssl 文件（由 acme.sh docker 生成）到 synology DSM 7.2

#### 0. help info // 帮助信息
# 输出当前时间
# output current datetime
date

####1. acme SSL -> docker jellyfin SSL
# 设置acme.sh 生成SSL路径
# Set acme.sh to generate SSL path
original_ssl_path="/volume1/docker/ee_acme_3.1.0/lib00.com_ecc"

# 设置docker jellyfin ssl证书存放路径
# Set the docker jellyfin ssl certificate storage path
target_docker_jellyfin_ssl_path="/volume1/docker/jellyfin_ny/config/ssl"

# 使用SSL证书生成PFX证书, Jellyfin使用PFX格式证书
# Generate a PFX certificate using SSL certificate. Jellyfin use PFX format certificate.
openssl pkcs12 -export -out "${original_ssl_path}/encode_pfx_lib00.com.pfx" -inkey "${original_ssl_path}/lib00.com.key" -in "${original_ssl_path}/lib00.com.cer" -password pass:dpit2024

# 执行ssl替换操作
# Perform ssl replacement operation
cp -r "${original_ssl_path}/encode_pfx_lib00.com.pfx" "${target_docker_jellyfin_ssl_path}/encode_pfx_lib00.com.pfx"

# 重启docker jellyfin服务, 使新SSL文件生效
# Restart the docker jellyfin service to make the new SSL file take effect
docker restart ee-nyanmisaka-jellyfin