#!/bin/bash
# author: dpit(https://dpit.lib00.com)
# this sh file for auto renew ssl file(generated by acme.sh docker) to synology DSM 7.2
# 此 sh 文件用于自动更新 ssl 文件（由 acme.sh docker 生成）到 synology DSM 7.2

#### 0. help info // 帮助信息
# 输出当前时间
# output current datetime
date

#### 1. acme SSL -> DSM SSL
# 设置acme.sh 生成SSL路径
# Set acme.sh to generate SSL path
original_ssl_path="/volume1/docker/ee_acme_3.1.0/lib00.com_ecc"

# 设置替换SSL路径
# Set the replacement SSL path
target_dsm_ssl_path="/usr/syno/etc/certificate/_archive/YKv5fl"

# 执行ssl替换操作
# Perform ssl replacement operation
cp -r "${original_ssl_path}/lib00.com.cer" "${target_dsm_ssl_path}/cert.pem"
cp -r "${original_ssl_path}/lib00.com.key" "${target_dsm_ssl_path}/privkey.pem"
cp -r "${original_ssl_path}/fullchain.cer" "${target_dsm_ssl_path}/fullchain.pem"

# 使用nginx reload命令, 使新SSL文件生效
# use nginx reload command to make the new SSL file take effect
synow3tool --gen-all && systemctl reload nginx